version: '3.3'

services:
  pg:
    build: .
    volumes:
      - .:/tmp/pagila-hw
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
